import gradio as gr
import speech_recognition as sr
from deep_translator import GoogleTranslator, MyMemoryTranslator
import warnings

warnings.filterwarnings("ignore")

def translate_speech(audio_filepath, target_language_code):
    if not audio_filepath:
        return "No audio provided.", ""
        
    recognizer = sr.Recognizer()
    
    try:
        # Load the audio file generated by Gradio
        with sr.AudioFile(audio_filepath) as source:
            audio = recognizer.record(source)
            
        # Convert speech to text
        text = recognizer.recognize_google(audio)
        
        # Translate the text using MyMemoryTranslator to bypass Google rate limits
        translator = MyMemoryTranslator(source='english', target=target_language_code)
        translated_text = translator.translate(text)
        
        return text, translated_text

    except sr.UnknownValueError:
        return "Error: Could not understand the audio.", ""
    except sr.RequestError as e:
        return f"Error: Speech recognition service unavailable; {e}", ""
    except Exception as e:
        return f"An error occurred: {e}", ""

# Gradio Interface
interface = gr.Interface(
    fn=translate_speech,
    inputs=[
        gr.Audio(sources=["microphone"], type="filepath", label="Speak Here"),
        gr.Dropdown(
            choices=["spanish", "french", "german", "hindi", "japanese", "chinese", "russian", "italian"], 
            value="spanish", 
            label="Target Language"
        )
    ],
    outputs=[
        gr.Textbox(label="Original Transcribed Text"),
        gr.Textbox(label="Translated Text")
    ],
    title="Speech Translator Web App",
    description="Record your voice, and it will transcribe and translate it into your chosen language."
)

if __name__ == "__main__":
    # share=True creates a public URL
    interface.launch(share=True, server_name="0.0.0.0")
